created Cloud Storage for Flutter web

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -137,7 +137,7 @@ jobs:
   
       - name: Verify GCS bucket access
         run: |
-          gsutil ls gs://web-flutter-gov-bucket/ || { echo "Error: Unable to access bucket gs://web-flutter-gov-bucket/."; exit 1; }
+          gsutil ls gs://web-flutter-gov-bucket || { echo "Error: Unable to access bucket gs://web-flutter-gov-bucket/."; exit 1; }
   
       - name: Deploy Flutter Web App to Google Cloud Storage
         run: |
