created Cloud Storage for Flutter web

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -104,23 +104,35 @@ jobs:
         with:
           credentials_json: ${{ secrets.GCP_CREDENTIALS }}
   
-      - name: Debug Authentication
+      - name: Download Flutter Web build artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: flutter-web-build
+          path: app/build/web
+  
+      - name: Verify build directory exists
         run: |
-          echo "Checking credentials..."
-          cat $GOOGLE_APPLICATION_CREDENTIALS
-          gcloud auth list
-          gcloud config list
-          ls -l $GOOGLE_APPLICATION_CREDENTIALS
+          if [ ! -d "app/build/web" ]; then
+            echo "Error: Directory app/build/web does not exist."
+            exit 1
+          fi
   
-      - name: Manually Authenticate to GCP
-        run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
+      - name: Check directory contents
+        run: |
+          if [ -z "$(ls -A app/build/web)" ]; then
+            echo "Error: Directory app/build/web is empty."
+            exit 1
+          fi
   
-      - name: Verify GCP Authentication
-        run: gcloud auth list
+      - name: Debug Path
+        run: |
+          echo "Current directory: $(pwd)"
+          echo "Contents of app/build/web:"
+          ls -l app/build/web
   
       - name: Deploy Flutter Web App to Google Cloud Storage
         run: |
-          gsutil -m rsync -R app/build/web/ gs://web-flutter-gov-bucket
+          gsutil -m rsync -R app/build/web/ gs://web-flutter-gov-bucket/
 
       # Step 6: Deploy API to Cloud Run (if applicable)
       - name: Deploy to Cloud Run (government-assistant-api)
